# name: Shared Build and Deploy

# on:
#   push:
#     branches:
#       - '**'
#   pull_request:
#     branches:
#       - '**'
#   workflow_dispatch:

# # Ajuste os valores abaixo e o nome do repositório do workflow reutilizável.
# env:
#   NOME_PROJETO: minha-aplicacao
#   NOME_SISTEMA: plataforma-x
#   DOTNET_PROJECT_FILE: src/MinhaApp/MinhaApp.csproj
#   PUBLISH_DIRECTORY: ./publish/minha-aplicacao
#   DOCKERFILE_PATH: docker/MinhaApp.Dockerfile
#   KUBERNETES_TEMPLATE: Workflows_BETA_PIPELINE/kubernetes/minhaaplicacao-deployment.yaml
#   CONTAINER_NAME: minhaaplicacao

# jobs:
#   call-shared-pipeline:
#     uses: ./.github/workflows/app-dispatcher.yml@main
#     with:
#       nome_projeto: ${{ env.NOME_PROJETO }}
#       nome_sistema: ${{ env.NOME_SISTEMA }}
#       dotnet_project_file: ${{ env.DOTNET_PROJECT_FILE }}
#       publish_directory: ${{ env.PUBLISH_DIRECTORY }}
#       dockerfile_path: ${{ env.DOCKERFILE_PATH }}
#       kubernetes_template: ${{ env.KUBERNETES_TEMPLATE }}
#       container_name: ${{ env.CONTAINER_NAME }}
#     secrets:
#       docker_username: ${{ secrets.DOCKER_USERNAME }}
#       docker_password: ${{ secrets.DOCKER_PASSWORD }}
#       kubeconfig_b64: ${{ secrets.KUBECONFIG_B64 }}
#       url_key_vault: ${{ secrets.URL_KEY_VAULT }}
