apiVersion: v1
kind: Secret
metadata:
  name: __CONTAINER_NAME__-secret
type: Opaque
data:
  KeyVault__Url: __URL_KEY_VAULT__
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: __CONTAINER_NAME__
  labels:
    app: __CONTAINER_NAME__
spec:
  replicas: 1
  selector:
    matchLabels:
      app: __CONTAINER_NAME__
  template:
    metadata:
      labels:
        app: __CONTAINER_NAME__
    spec:
      containers:
      - name: __CONTAINER_NAME__
        image: __IMAGE__
        ports:
        - containerPort: 80
        env:
        - name: AzureWebJobsStorage
          value: "<your-storage-connection-string>"
        - name: FUNCTIONS_WORKER_RUNTIME
          value: "dotnet"
